apiVersion: v1
kind: Secret
metadata:
  name: auto-tuner-db-credentials
  namespace: default
type: Opaque
data:
  username: cG9zdGdyZXM= # postgres
  password: cG9zdGdyZXM= # postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auto-tuner-db
  namespace: default
spec:
  serviceName: "auto-tuner-db"
  replicas: 1
  selector:
    matchLabels:
      app: auto-tuner-db
  template:
    metadata:
      labels:
        app: auto-tuner-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: deployment_history
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auto-tuner-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auto-tuner-db-credentials
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: auto-tuner-data
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: auto-tuner-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auto-tuner-db
  namespace: default
spec:
  selector:
    app: auto-tuner-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
