apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-tuner-code
  namespace: default
data:
  model.py: |
    # Content of model.py goes here
  data_manager.py: |
    # Content of data_manager.py goes here
  controller.py: |
    # Content of controller.py goes here
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auto-tuner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-auto-tuner
  template:
    metadata:
      labels:
        app: deployment-auto-tuner
    spec:
      serviceAccountName: deployment-tuner-sa
      containers:
        - name: auto-tuner
          image: python:3.9
          command: ["/bin/sh", "-c"]
          args:
            - |
              pip install kubernetes pandas scikit-learn joblib psycopg2-binary requests && \
              mkdir -p /app && \
              cp /config/model.py /app/ && \
              cp /config/data_manager.py /app/ && \
              cp /config/controller.py /app/ && \
              cd /app && \
              python controller.py
          volumeMounts:
            - name: auto-tuner-code
              mountPath: /config
          env:
            - name: DB_HOST
              value: "auto-tuner-db"
            - name: DB_NAME
              value: "deployment_history"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auto-tuner-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auto-tuner-db-credentials
                  key: password
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: auto-tuner-code
          configMap:
            name: auto-tuner-code
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-tuner-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-modifier
  namespace: default
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-tuner-rollout-modifier
  namespace: default
subjects:
  - kind: ServiceAccount
    name: deployment-tuner-sa
roleRef:
  kind: Role
  name: rollout-modifier
  apiGroup: rbac.authorization.k8s.io
