apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auto-tuner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-auto-tuner
  template:
    metadata:
      labels:
        app: deployment-auto-tuner
    spec:
      serviceAccountName: deployment-tuner-sa
      containers:
        - name: auto-tuner
          image: python:3.9
          command: ["python", "/app/controller.py"]
          volumeMounts:
            - name: app-code
              mountPath: /app
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: app-code
          configMap:
            name: auto-tuner-code
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-tuner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rollout-modifier
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-tuner-rollout-modifier
subjects:
  - kind: ServiceAccount
    name: deployment-tuner-sa
roleRef:
  kind: Role
  name: rollout-modifier
  apiGroup: rbac.authorization.k8s.io
