apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-tuner-config
data:
  config.yaml: |
    analysis:
      metrics:
        - name: success-rate
          weight: 0.4
          threshold: 0.95
          query: sum(irate(http_requests_total{service="smu-service",status=~"2.."}[1m])) / sum(irate(http_requests_total{service="smu-service"}[1m]))
        
        - name: latency
          weight: 0.3
          threshold: 300
          query: histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket{service="smu-service"}[1m])) by (le))
        
        - name: memory-usage
          weight: 0.15
          threshold: 100
          query: sum(container_memory_usage_bytes{pod=~"smu-rollout-.*"}) / 1024 / 1024
        
        - name: cpu-usage
          weight: 0.15
          threshold: 150
          query: sum(rate(container_cpu_usage_seconds_total{pod=~"smu-rollout-.*"}[1m])) * 1000

    tuning:
      learning_rate: 0.05
      decision_threshold: 0.75
      sampling_interval: 60
      history_window: 10
      
    recommendation:
      rollback_threshold: 0.4
      promotion_threshold: 0.8
