apiVersion: apps/v1
kind: Deployment
metadata:
  name: smu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smu
  template:
    metadata:
      labels:
        app: smu
    spec:
      containers:
        - name: smu-container
          image: ghcr.io/karan-wakade/smu:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          envFrom:
            - secretRef:
                name: smu-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
