apiVersion: v1
kind: Service
metadata:
  name: smu-service
spec:
  selector:
    app: smu
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: smu-canary-svc
spec:
  selector:
    app: smu
    # This will match pods managed by the canary ReplicaSet
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: smu-stable-svc
spec:
  selector:
    app: smu
    # This will match pods managed by the stable ReplicaSet
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
