apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: staging-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smu
      environment: staging
  template:
    metadata:
      labels:
        app: smu
        environment: staging
    spec:
      containers:
        - name: smu
          image: ghcr.io/karan-wakade/smu:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 30s }
      canaryService: smu-staging-canary-svc
      stableService: smu-staging-stable-svc
