apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: smu-frontend
  namespace: smu-system
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: smu-frontend
  template:
    metadata:
      labels:
        app: smu-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/karan-wakade/smu/frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        startingStep: 2
        args:
          - name: service-name
            value: smu-frontend-service
      steps:
        - setWeight: 20
        - pause: { duration: 1m }
        - setWeight: 40
        - pause: { duration: 1m }
        - setWeight: 60
        - pause: { duration: 1m }
        - setWeight: 80
        - pause: { duration: 1m }
  # service:
  #   port: 80
  #   targetPort: 80
  #   name: http
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: smu-system
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 2
      successCondition: result[0] >= 0.95
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{service="{{args.service-name}}",status!~"5.."}[1m])) / 
            sum(rate(http_requests_total{service="{{args.service-name}}"}[1m]))
---
kind: Service
apiVersion: v1
metadata:
  name: smu-frontend-service
  namespace: smu-system
spec:
  selector:
    app: smu-frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
