apiVersion: apps/v1
kind: Deployment
metadata:
  name: smu-app-canary
  labels:
    app: smu-canary
    canary_percentage: 20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smu-canary
  template:
    metadata:
      labels:
        app: smu-canary
    spec:
      containers:
      - name: smu-app
        image: ghcr.io/karan-wakade/smu:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smu-app-canary
spec:
  selector:
    app: smu-canary
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP