apiVersion: v1
kind: Service
metadata:
  name: smu-frontend-service
  namespace: smu-system
  labels:
    app: smu-frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: smu-frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: smu-system
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ /index.html;
        }
        
        location /api {
            proxy_pass http://smu-backend-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /metrics {
            default_type text/plain;
            content_by_lua_file /usr/share/nginx/html/metrics-exporter.js;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }
