name: Continuous Deployment

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Kubernetes connection
        run: |
          $env:KUBECONFIG = "$PWD\.github\kubeconfig\config"

          # Test connection with longer timeout
          kubectl get nodes --request-timeout=30s

      - name: Deploy standard release
        run: |
          $env:KUBECONFIG = "$PWD\.github\kubeconfig\config"

          # Apply base configurations
          kubectl apply -f k8s/base/ --request-timeout=30s

          # Update deployment with new image
          kubectl set image deployment/smu-app smu-container=karan-wakade/smu:${{ github.sha }} --request-timeout=30s

          # Monitor rollout
          kubectl rollout status deployment/smu-app --timeout=5m --request-timeout=30s
