name: CI Pipeline

on:
  push:
    branches: [main, develop, deploy]
  pull_request:
    branches: [main, develop, deploy]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install and test frontend
        run: |
          cd frontend
          npm ci
          npm test -- --watchAll=false --ci

      - name: Install and test backend
        run: |
          cd backend
          npm ci
          npm test
