name: Deploy Canary

on:
  workflow_dispatch:
    inputs:
      percentage:
        description: 'Percentage of traffic to route to canary'
        required: true
        default: '20'

jobs:
  deploy-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setup minikube with more reliable configuration
      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 1.28.0
          kubernetes-version: v1.23.0
          driver: docker
          start-args: --memory=2048mb --cpus=2
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      # Configure kubectl
      - name: Configure kubectl
        run: |
          minikube update-context
          kubectl get nodes
      
      # Pull the image
      - name: Pull image into minikube
        run: |
          minikube image pull ghcr.io/${{ github.repository }}:latest
      
      # Deploy canary
      - name: Deploy Canary
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace smu --dry-run=client -o yaml | kubectl apply -f -
          
          # Update canary percentage
          sed -i "s/canary_percentage:.*/canary_percentage: ${{ github.event.inputs.percentage }}/" k8s/canary/deployment.yaml
          
          # Apply canary deployment
          kubectl apply -f k8s/canary/deployment.yaml -n smu
          
          # Wait for deployment
          kubectl rollout status deployment/smu-app-canary -n smu --timeout=120s