name: Deploy Canary

on:
  workflow_dispatch:
    inputs:
      percentage:
        description: 'Percentage of traffic to route to canary'
        required: true
        default: '20'

jobs:
  deploy-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Replace Kind setup with Minikube
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 1.28.0
          driver: docker
          kubernetes-version: v1.26.3
      
      # Configure kubectl
      - name: Configure kubectl
        run: |
          minikube update-context
          kubectl config use-context minikube
      
      # Deploy canary
      - name: Deploy Canary
        run: |
          # Update canary percentage if needed
          sed -i "s/canary_percentage:.*/canary_percentage: ${{ github.event.inputs.percentage }}/" k8s/canary/deployment.yaml
          # Apply canary deployment
          kubectl apply -f k8s/canary/deployment.yaml
          # Wait for deployment
          kubectl rollout status deployment/smu-app-canary
      
      # Setup monitoring
      - name: Setup Monitoring
        run: |
          # Install Prometheus and Grafana for monitoring
          kubectl apply -f k8s/monitoring/prometheus.yaml
          kubectl apply -f k8s/monitoring/grafana.yaml
          # Wait for Grafana to be ready
          kubectl rollout status deployment/grafana -n monitoring